Layout/LineLength:
  Max: 80

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/MethodName:
  EnforcedStyle: snake_case
Naming/VariableName:
  EnforcedStyle: snake_case

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Layout/EmptyLinesAroundClassBody:
  Enabled: true
Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Style/RedundantReturn:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/GuardClause:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/For:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "[]"
    "%w": "[]"

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Metrics/ClassLength:
  Max: 100
Metrics/LineLength:
  Max: 100

Style/SafeNavigation:
  Enabled: true
