start_url: "https://24ka.com.ua/ua/g134495122-bolgarki"
base_url: "https://24ka.com.ua"
product_link_selector: "//a[@class='cs-goods-title']"
name_selector: "//h1//span['text']"
price_selector: "//p[@class='b-product-cost__price']"
description_selector: "//div[@class='b-user-content']//p//span"
image_selector: ".cs-pictures__img"
category: "24ka"
database_type: 'sqlite'
sqlite_path: 'db/my_database.sqlite'
mongodb_uri: 'mongodb+srv://admin:admin@cluster0.iuyo3.mongodb.net/'
mongodb_database: 'my_mongo_database'
